import json

cells = [
{"cell_type":"markdown","id":"01","metadata":{},"source":["# Sierra Leone Renewable Energy UQ Analysis — V2 (Real Data)\n","**Author:** Kenneth Bamba | **Year:** 2026\n\n","This notebook uses real NASA POWER data for 5 Sierra Leone locations.\n"]},
{"cell_type":"code","execution_count":None,"id":"02","metadata":{},"outputs":[],"source":["import numpy as np\nimport pandas as pd\nimport scipy.stats as stats\nimport matplotlib\nmatplotlib.use('Agg')\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport warnings, json, time, os\nfrom urllib import request\nfrom SALib.sample import saltelli\nfrom SALib.analyze import sobol\n\nnp.random.seed(42)\nos.makedirs('data', exist_ok=True)\nos.makedirs('figures', exist_ok=True)\n\nLOCATIONS = {\n    'Freetown': {'lat': 8.4657, 'lon': -13.2317},\n    'Bo':       {'lat': 7.9647, 'lon': -11.7383},\n    'Kenema':   {'lat': 7.8767, 'lon': -11.1900},\n    'Makeni':   {'lat': 8.8845, 'lon': -12.0444},\n    'Koidu':    {'lat': 8.6400, 'lon': -10.9700},\n}\n\nprint('Setup complete.')\n"]},
{"cell_type":"markdown","id":"03","metadata":{},"source":["## Section 1 — Data Acquisition (NASA POWER API)\n","Downloads 22 years of real daily solar and wind data for each study location.\n"]},
{"cell_type":"code","execution_count":None,"id":"04","metadata":{},"outputs":[],"source":["def fetch_nasa_power(lat, lon, start='20010101', end='20221231'):\n    params = 'ALLSKY_SFC_SW_DWN,WS10M,WS50M,T2M,RH2M'\n    url = (f'https://power.larc.nasa.gov/api/temporal/daily/point'\n           f'?parameters={params}&community=RE'\n           f'&longitude={lon}&latitude={lat}'\n           f'&start={start}&end={end}&format=JSON')\n    req = request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n    with request.urlopen(req, timeout=60) as r:\n        data = json.loads(r.read())\n    p = data['properties']['parameter']\n    df = pd.DataFrame(p)\n    df.index = pd.to_datetime(df.index, format='%Y%m%d')\n    df.index.name = 'date'\n    df.columns = ['GHI','WS10M','WS50M','T2M','RH2M']\n    df.replace(-999, np.nan, inplace=True)\n    df.interpolate(inplace=True)\n    return df\n\ndatasets = {}\nfor name, coords in LOCATIONS.items():\n    fpath = f'data/{name.lower()}_nasa.csv'\n    if os.path.exists(fpath):\n        df = pd.read_csv(fpath, index_col=0, parse_dates=True)\n        print(f'{name}: loaded from cache ({len(df)} days)')\n    else:\n        print(f'{name}: downloading...')\n        df = fetch_nasa_power(coords['lat'], coords['lon'])\n        df.to_csv(fpath)\n        print(f'{name}: saved {len(df)} days')\n        time.sleep(2)\n    datasets[name] = df\n\nprint('All data ready.')\n"]},
{"cell_type":"markdown","id":"05","metadata":{},"source":["## Section 2 — Exploratory Analysis\n"]},
{"cell_type":"code","execution_count":None,"id":"06","metadata":{},"outputs":[],"source":["df = datasets['Freetown'].copy()\ndf['Kt'] = df['GHI'] / df['GHI'].max()  # simplified clearness proxy\n\nfig, axes = plt.subplots(2, 2, figsize=(14, 8))\nfig.suptitle('Freetown — 22-Year Daily Climate (2001-2022)', fontsize=14, fontweight='bold')\n\ndf['GHI'].resample('ME').mean().plot(ax=axes[0,0], color='orange')\naxes[0,0].set_title('Monthly Mean GHI (kWh/m²/day)')\naxes[0,0].set_ylabel('GHI')\n\ndf['WS50M'].resample('ME').mean().plot(ax=axes[0,1], color='steelblue')\naxes[0,1].set_title('Monthly Mean Wind Speed at 50m (m/s)')\naxes[0,1].set_ylabel('WS50M')\n\ndf['T2M'].resample('ME').mean().plot(ax=axes[1,0], color='red')\naxes[1,0].set_title('Monthly Mean Temperature (°C)')\naxes[1,0].set_ylabel('T2M')\n\ndf['RH2M'].resample('ME').mean().plot(ax=axes[1,1], color='green')\naxes[1,1].set_title('Monthly Mean Relative Humidity (%)')\naxes[1,1].set_ylabel('RH2M')\n\nplt.tight_layout()\nplt.savefig('figures/01_time_series.png', dpi=150)\nplt.close()\nprint('Figure 1 saved: figures/01_time_series.png')\nprint(df.describe().round(3))\n"]},
{"cell_type":"code","execution_count":None,"id":"07","metadata":{},"outputs":[],"source":["df['month'] = df.index.month\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\nfig.suptitle('Freetown — Monthly Resource Distribution (2001-2022)', fontsize=13, fontweight='bold')\n\ndf.boxplot(column='GHI', by='month', ax=axes[0])\naxes[0].set_title('GHI (kWh/m²/day)')\naxes[0].set_xlabel('Month')\n\ndf.boxplot(column='WS50M', by='month', ax=axes[1])\naxes[1].set_title('Wind Speed 50m (m/s)')\naxes[1].set_xlabel('Month')\n\nplt.suptitle('')\nplt.tight_layout()\nplt.savefig('figures/02_seasonal_boxplots.png', dpi=150)\nplt.close()\nprint('Figure 2 saved: figures/02_seasonal_boxplots.png')\n"]},
{"cell_type":"markdown","id":"08","metadata":{},"source":["## Section 3 — Solar Resource UQ (Beta Distribution)\n"]},
{"cell_type":"code","execution_count":None,"id":"09","metadata":{},"outputs":[],"source":["# Clearness index: Kt = GHI / extraterrestrial irradiance (approx)\n# Simple proxy: normalise GHI to [0,1] range\nghi = df['GHI'].dropna().values\nKt = ghi / ghi.max()\nKt = Kt[(Kt > 0.01) & (Kt < 0.99)]  # keep valid range for Beta\n\nalpha_mle, beta_mle, loc, scale = stats.beta.fit(Kt, floc=0, fscale=1)\nks_stat, ks_p = stats.kstest(Kt, 'beta', args=(alpha_mle, beta_mle))\n\nprint(f'Beta MLE fit: alpha={alpha_mle:.3f}, beta={beta_mle:.3f}')\nprint(f'KS test: statistic={ks_stat:.4f}, p-value={ks_p:.4f}')\nprint(f'Fit is {\"GOOD\" if ks_p > 0.05 else \"POOR\"} (p {\">\"> 0.05} 0.05)' )\n\nfig, ax = plt.subplots(figsize=(9, 5))\nx = np.linspace(0, 1, 200)\nax.hist(Kt, bins=50, density=True, alpha=0.5, color='orange', label='Observed Kt')\nax.plot(x, stats.beta.pdf(x, alpha_mle, beta_mle), 'r-', lw=2,\n        label=f'Beta(α={alpha_mle:.2f}, β={beta_mle:.2f})')\nax.set_xlabel('Clearness Index (Kt)')\nax.set_ylabel('Density')\nax.set_title('Freetown — Beta Distribution Fit to Clearness Index')\nax.legend()\nplt.tight_layout()\nplt.savefig('figures/03_beta_fit_solar.png', dpi=150)\nplt.close()\nprint('Figure 3 saved.')\n"]},
{"cell_type":"markdown","id":"10","metadata":{},"source":["## Section 4 — Wind Resource UQ (Weibull Distribution)\n"]},
{"cell_type":"code","execution_count":None,"id":"11","metadata":{},"outputs":[],"source":["ws = df['WS50M'].dropna().values\nws = ws[ws > 0]\n\n# Method 1: MLE\nshape_mle, loc_mle, scale_mle = stats.weibull_min.fit(ws, floc=0)\n# Method 2: Method of Moments\nmean_ws, std_ws = ws.mean(), ws.std()\n# Weibull MOM approximation\nk_mom = (std_ws / mean_ws) ** -1.086\nc_mom = mean_ws / stats.gamma(1 + 1/k_mom)\n# Method 3: Energy Pattern Factor\nepf = np.mean(ws**3) / np.mean(ws)**3\nk_epf = 1 + 3.69 / epf**2\nc_epf = mean_ws / stats.gamma(1 + 1/k_epf)\n# Method 4: Empirical (Justus)\nk_emp = (std_ws / mean_ws) ** -1.086\nc_emp = mean_ws / (0.568 + 0.434/k_emp)**(1/k_emp)\n\nprint('Weibull parameter estimates:')\nprint(f'  MLE:      k={shape_mle:.3f}, c={scale_mle:.3f}')\nprint(f'  MOM:      k={k_mom:.3f}, c={c_mom:.3f}')\nprint(f'  EPF:      k={k_epf:.3f}, c={c_epf:.3f}')\nprint(f'  Empirical:k={k_emp:.3f}, c={c_emp:.3f}')\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 5))\nx = np.linspace(0, ws.max(), 300)\n\naxes[0].hist(ws, bins=50, density=True, alpha=0.4, color='steelblue', label='Observed')\nfor k, c, label in [(shape_mle, scale_mle,'MLE'),(k_mom,c_mom,'MOM'),\n                     (k_epf,c_epf,'EPF'),(k_emp,c_emp,'Empirical')]:\n    axes[0].plot(x, stats.weibull_min.pdf(x, k, 0, c), lw=1.5, label=f'{label} k={k:.2f}')\naxes[0].set_xlabel('Wind Speed (m/s)')\naxes[0].set_title('Weibull PDF — 4 Methods')\naxes[0].legend(fontsize=8)\n\n# Q-Q plot for MLE\n(osm, osr), (slope, intercept, r) = stats.probplot(ws, dist=stats.weibull_min,\n                                                     sparams=(shape_mle,0,scale_mle))\naxes[1].scatter(osm, osr, s=2, alpha=0.3, color='steelblue')\naxes[1].plot([osm.min(),osm.max()],[osm.min(),osm.max()],'r--', label=f'R²={r**2:.4f}')\naxes[1].set_xlabel('Theoretical Quantiles')\naxes[1].set_ylabel('Sample Quantiles')\naxes[1].set_title('Q-Q Plot (MLE Weibull)')\naxes[1].legend()\n\nplt.tight_layout()\nplt.savefig('figures/04_weibull_fit_wind.png', dpi=150)\nplt.close()\nprint('Figure 4 saved.')\n"]},
{"cell_type":"markdown","id":"12","metadata":{},"source":["## Section 5 — Monte Carlo Energy Yield Simulation\n"]},
{"cell_type":"code","execution_count":None,"id":"13","metadata":{},"outputs":[],"source":["N = 10000\nPV_KW = 500\nWIND_KW = 200\n\n# Uncertainty parameters (based on literature)\nghi_mean  = df['GHI'].mean() * 365  # kWh/m2/yr\nghi_sigma = ghi_mean * 0.08          # 8% reanalysis bias\nws_mean   = df['WS50M'].mean()\nws_sigma  = ws_mean * 0.10           # 10% wind speed uncertainty\n\n# Monte Carlo draws\nghi_samples = np.random.normal(ghi_mean, ghi_sigma, N)\nws_samples  = np.random.normal(ws_mean, ws_sigma, N)\nPR_samples  = np.random.normal(0.75, 0.05, N)    # Performance Ratio\ncf_wind     = np.random.normal(0.22, 0.04, N)    # Wind capacity factor\n\n# Energy yield (MWh/yr)\nPV_yield   = ghi_samples * PR_samples * PV_KW / 1000\nWind_yield = cf_wind * WIND_KW * 8760 / 1000\nTotal      = PV_yield + Wind_yield\n\n# Exceedance probabilities\np_values = [50, 75, 90]\nfor p in p_values:\n    print(f'P{p} Total AEP: {np.percentile(Total, 100-p):.1f} MWh/yr')\n\nprint(f'Mean: {Total.mean():.1f} MWh/yr')\nprint(f'Std:  {Total.std():.1f} MWh/yr ({Total.std()/Total.mean()*100:.1f}%)')\nprint(f'P90/P50 ratio: {np.percentile(Total,10)/np.percentile(Total,50):.3f}')\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 5))\naxes[0].hist(Total, bins=80, color='steelblue', edgecolor='white', alpha=0.8)\nfor p, c in zip(p_values, ['green','orange','red']):\n    v = np.percentile(Total, 100-p)\n    axes[0].axvline(v, color=c, lw=2, label=f'P{p}={v:.0f} MWh')\naxes[0].set_xlabel('Annual Energy Production (MWh/yr)')\naxes[0].set_title(f'Monte Carlo AEP Distribution (N={N:,})')\naxes[0].legend()\n\nsorted_t = np.sort(Total)[::-1]\nexc = np.arange(1, N+1) / N * 100\naxes[1].plot(exc, sorted_t, color='navy')\naxes[1].set_xlabel('Exceedance Probability (%)')\naxes[1].set_ylabel('AEP (MWh/yr)')\naxes[1].set_title('P-Exceedance Curve')\naxes[1].invert_xaxis()\naxes[1].grid(alpha=0.3)\n\nplt.tight_layout()\nplt.savefig('figures/05_monte_carlo_aep.png', dpi=150)\nplt.close()\nprint('Figure 5 saved.')\n"]},
{"cell_type":"markdown","id":"14","metadata":{},"source":["## Section 6 — Global Sensitivity Analysis (Sobol)\n"]},
{"cell_type":"code","execution_count":None,"id":"15","metadata":{},"outputs":[],"source":["problem = {\n    'num_vars': 5,\n    'names': ['GHI_bias','PV_perf_ratio','Wind_speed_bias','Wind_cf','PV_capacity_kW'],\n    'bounds': [[ghi_mean*0.84, ghi_mean*1.16],\n               [0.65, 0.85],\n               [ws_mean*0.80, ws_mean*1.20],\n               [0.14, 0.30],\n               [400, 600]]\n}\n\nparam_values = saltelli.sample(problem, 512, calc_second_order=False)\n\ndef aep_model(X):\n    ghi_b, pr, ws_b, cf_w, pv_kw = X[:,0],X[:,1],X[:,2],X[:,3],X[:,4]\n    pv  = ghi_b * pr * pv_kw / 1000\n    wnd = cf_w * WIND_KW * 8760 / 1000\n    return pv + wnd\n\nY = aep_model(param_values)\nSi = sobol.analyze(problem, Y, calc_second_order=False, print_to_console=False)\n\nnames = problem['names']\nS1 = Si['S1']\nST = Si['ST']\n\nprint('Sobol Sensitivity Indices:')\nfor n, s1, st in zip(names, S1, ST):\n    print(f'  {n:25s}  S1={s1:.3f}  ST={st:.3f}')\n\nfig, ax = plt.subplots(figsize=(9, 5))\nx = np.arange(len(names))\nax.barh([n.replace('_',' ') for n in names], ST, alpha=0.8, color='navy', label='Total effect (ST)')\nax.barh([n.replace('_',' ') for n in names], S1, alpha=0.8, color='steelblue', label='First order (S1)')\nax.set_xlabel('Sobol Index')\nax.set_title('Global Sensitivity Analysis — AEP Variance Decomposition')\nax.legend()\nax.axvline(0, color='black', lw=0.5)\nplt.tight_layout()\nplt.savefig('figures/06_sobol_sensitivity.png', dpi=150)\nplt.close()\nprint('Figure 6 saved.')\n"]},
{"cell_type":"markdown","id":"16","metadata":{},"source":["## Section 7 — Multi-Location Comparison\n"]},
{"cell_type":"code","execution_count":None,"id":"17","metadata":{},"outputs":[],"source":["summary = []\nfor name, df_loc in datasets.items():\n    annual_ghi  = df_loc['GHI'].resample('YE').sum()\n    mean_ghi    = annual_ghi.mean()\n    cv_ghi      = annual_ghi.std() / annual_ghi.mean() * 100\n    mean_ws50   = df_loc['WS50M'].mean()\n    k, loc_, c  = stats.weibull_min.fit(df_loc['WS50M'].dropna().values[df_loc['WS50M'].dropna().values > 0], floc=0)\n    cf          = float(stats.weibull_min.mean(k, loc_, c)) / df_loc['WS50M'].mean() * 0.22  # rough proxy\n    summary.append({'Site': name, 'Annual_GHI_kWh': round(mean_ghi,1),\n                    'CV_GHI_%': round(cv_ghi,2), 'Mean_WS50_ms': round(mean_ws50,2),\n                    'Weibull_k': round(k,3), 'Weibull_c': round(c,3)})\n\nresults = pd.DataFrame(summary).set_index('Site')\nresults.to_csv('data/multi_location_summary.csv')\nprint(results.to_string())\n\nfig, axes = plt.subplots(1, 3, figsize=(15, 5))\nfig.suptitle('Sierra Leone — 5-Location Resource Comparison', fontsize=13, fontweight='bold')\n\nresults['Annual_GHI_kWh'].plot.bar(ax=axes[0], color='orange', alpha=0.8, rot=30)\naxes[0].set_title('Mean Annual GHI (kWh/m²/yr)')\naxes[0].set_ylabel('kWh/m²/yr')\n\nresults['CV_GHI_%'].plot.bar(ax=axes[1], color='steelblue', alpha=0.8, rot=30)\naxes[1].set_title('Inter-annual GHI Variability (CV %)')\naxes[1].set_ylabel('CV (%)')\n\nresults['Mean_WS50_ms'].plot.bar(ax=axes[2], color='green', alpha=0.8, rot=30)\naxes[2].set_title('Mean Wind Speed at 50m (m/s)')\naxes[2].set_ylabel('m/s')\n\nplt.tight_layout()\nplt.savefig('figures/07_multi_location.png', dpi=150)\nplt.close()\nprint('Figure 7 saved.')\n"]},
{"cell_type":"markdown","id":"18","metadata":{},"source":["## Summary\n"]},
{"cell_type":"code","execution_count":None,"id":"19","metadata":{},"outputs":[],"source":["print('='*60)\nprint('ANALYSIS COMPLETE — All outputs based on REAL NASA POWER data')\nprint('='*60)\nprint()\nprint('Figures saved to: figures/')\nfor f in sorted(os.listdir('figures')):\n    print(f'  {f}')\nprint()\nprint('Data files saved to: data/')\nfor f in sorted(os.listdir('data')):\n    print(f'  {f}')\n"]},
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "SL UQ Analysis (venv)", "language": "python", "name": "sl_uq_analysis"},
        "language_info": {"name": "python", "version": "3.13.0"}
    },
    "cells": cells
}

with open('/home/augie/Desktop/Projects/Kennetth_Projects/improved_project_docs/SL_UQ_Analysis_V2_RealData.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)

print("Notebook created successfully.")
